AWSTemplateFormatVersion: 2010-09-09
Description: utc-time-app-init
Transform:
- AWS::Serverless-2016-10-31
Globals:
  Api:
    OpenApiVersion: 3.0.1
Resources:
  getUtcTimeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: s3://utc-time-fn-artifacts/8f5c931b9726c2500247682807f8b136
      Handler: dist/src/handlers/get-utc-time.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get utc time
      AutoPublishAlias: version
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        Api:
          Type: Api
          Properties:
            Path: /utc-time
            Method: GET
            RestApiId:
              Ref: MyApi
            Auth:
              DefaultAuthorizer: MyLambdaTokenAuthorizer
              Authorizers:
                MyLambdaTokenAuthorizer:
                  FunctionArn:
                    Fn::GetAtt:
                    - myAuthFunction
                    - Arn
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  myAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://utc-time-fn-artifacts/33fb412ed31547b7460e78650ea99260
      Handler: dist/src/handlers/auth.handler
      Runtime: nodejs12.x
      AutoPublishAlias: version
      DeploymentPreference:
        Type: AllAtOnce
      Environment:
        Variables:
          SECRET_NAME: /utcDate/token
