AWSTemplateFormatVersion: 2010-09-09
Description: utc-time-app-init
Transform:
- AWS::Serverless-2016-10-31
Resources:
  getUtcTimeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: s3://utc-time-fn-artifacts/8d269067d3c2abec7d47831d09046e0d
      Handler: dist/src/handlers/get-utc-time.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get utc time
      AutoPublishAlias: version
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        Api:
          Type: Api
          Properties:
            Path: /utc-time
            Method: GET
            Auth:
              DefaultAuthorizer: MyLambdaTokenAuthorizer
              Authorizers:
                MyLambdaTokenAuthorizer:
                  FunctionArn:
                    Fn::GetAtt:
                    - myAuthFunction
                    - Arn
  myAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://utc-time-fn-artifacts/7a106dac8cf0a39030251fe57f2a6ff6
      Handler: dist/src/handlers/auth.handler
      Runtime: nodejs12.x
      AutoPublishAlias: version
      DeploymentPreference:
        Type: AllAtOnce
      Environment:
        Variables:
          SECRET_NAME: /utcDate/token
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
